Config header files moved.

diff --git a/trunk/sidplay/configure b/trunk/sidplay/configure
--- a/trunk/sidplay/configure
+++ b/trunk/sidplay/configure
@@ -14010,8 +14010,9 @@ install dir.  Please check your installation!
    { (exit 1); exit 1; }; };
 fi
 
-CXXFLAGS="$CXXFLAGS -DHAVE_UNIX -Wall \$(LIBSIDPLAY2_CXXFLAGS) \
-\$(LIBSIDUTILS_CXXFLAGS) \$(BUILDERS_CXXFLAGS)"
+CXXFLAGS="$CXXFLAGS -DHAVE_UNIX -Wall -I\$(top_srcdir)/include \
+\$(LIBSIDPLAY2_CXXFLAGS) \$(LIBSIDUTILS_CXXFLAGS) \
+\$(BUILDERS_CXXFLAGS)"
 
 ac_config_files="$ac_config_files Makefile doc/Makefile doc/en/Makefile src/Makefile src/audio/Makefile src/audio/alsa/Makefile src/audio/hpux/Makefile src/audio/irix/Makefile src/audio/mmsystem/Makefile src/audio/null/Makefile src/audio/oss/Makefile src/audio/sunos/Makefile src/audio/wav/Makefile unix/Makefile unix/sidplay2.spec"
 cat >confcache <<\_ACEOF
@@ -14093,7 +14094,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:14096: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:14097: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -14269,7 +14270,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:14272: error: ambiguous option: $1
+    { { echo "$as_me:14273: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -14288,7 +14289,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:14291: error: unrecognized option: $1
+  -*) { { echo "$as_me:14292: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -14350,7 +14351,7 @@ do
   "unix/sidplay2.spec" ) CONFIG_FILES="$CONFIG_FILES unix/sidplay2.spec" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "unix/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS unix/config.h" ;;
-  *) { { echo "$as_me:14353: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:14354: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -14614,7 +14615,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:14617: creating $ac_file" >&5
+    { echo "$as_me:14618: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -14632,7 +14633,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14635: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14636: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14645,7 +14646,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14648: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14649: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14706,7 +14707,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:14709: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:14710: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -14717,7 +14718,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14720: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14721: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14730,7 +14731,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14733: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14734: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14847,7 +14848,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:14850: $ac_file is unchanged" >&5
+      { echo "$as_me:14851: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
