Removed MOS6581 references.

diff --git a/libsidplay/configure b/libsidplay/configure
--- a/libsidplay/configure
+++ b/libsidplay/configure
@@ -15385,7 +15385,7 @@ fi
 
 CXXFLAGS="$CXXFLAGS -I\$(top_srcdir)/include/sidplay \$(RESID_INCLUDES) -Wall"
 
-ac_config_files="$ac_config_files libsidplay.spec Makefile include/Makefile include/sidplay/Makefile include/sidplay/sidconfig.h src/Makefile src/c64/Makefile src/mos6510/Makefile src/mos6526/Makefile src/mos656x/Makefile src/mos6581/Makefile src/sid6526/Makefile src/sidtune/Makefile src/sid6526/Makefile src/xsid/Makefile"
+ac_config_files="$ac_config_files libsidplay.spec Makefile include/Makefile include/sidplay/Makefile include/sidplay/sidconfig.h src/Makefile src/c64/Makefile src/mos6510/Makefile src/mos6526/Makefile src/mos656x/Makefile src/sid6526/Makefile src/sidtune/Makefile src/xsid/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -15715,14 +15715,12 @@ do
   "src/mos6510/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/mos6510/Makefile" ;;
   "src/mos6526/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/mos6526/Makefile" ;;
   "src/mos656x/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/mos656x/Makefile" ;;
-  "src/mos6581/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/mos6581/Makefile" ;;
   "src/sid6526/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/sid6526/Makefile" ;;
   "src/sidtune/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/sidtune/Makefile" ;;
-  "src/sid6526/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/sid6526/Makefile" ;;
   "src/xsid/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/xsid/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
-  *) { { echo "$as_me:15725: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:15723: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -15985,7 +15983,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:15988: creating $ac_file" >&5
+    { echo "$as_me:15986: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -16003,7 +16001,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:16006: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:16004: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -16016,7 +16014,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:16019: error: cannot find input file: $f" >&5
+           { { echo "$as_me:16017: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -16077,7 +16075,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:16080: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:16078: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -16088,7 +16086,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:16091: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:16089: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -16101,7 +16099,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:16104: error: cannot find input file: $f" >&5
+           { { echo "$as_me:16102: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -16218,7 +16216,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:16221: $ac_file is unchanged" >&5
+      { echo "$as_me:16219: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
