Added support for an all in one build with uncompiled libraries.

diff --git a/trunk/builders/hardsid-builder/configure b/trunk/builders/hardsid-builder/configure
--- a/trunk/builders/hardsid-builder/configure
+++ b/trunk/builders/hardsid-builder/configure
@@ -1018,6 +1018,7 @@ Optional Features:
   --enable-static=PKGS  build static libraries default=yes
   --enable-fast-install=PKGS  optimize for fast installation default=yes
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --disable-library-checks  do not check for working libraries
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4692,7 +4693,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4695 "configure"' > conftest.$ac_ext
+  echo '#line 4696 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5210,7 +5211,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5213: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5214: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6955,7 +6956,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6958 "configure"
+#line 6959 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7053,7 +7054,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7056 "configure"
+#line 7057 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7848,6 +7849,17 @@ _ACEOF
 
 
 
+    # Check whether --enable-library-checks or --disable-library-checks was given.
+if test "${enable_library_checks+set}" = set; then
+  enableval="$enable_library_checks"
+
+fi;
+    if test x"${enable_library_checks+set}" = xset; then
+        SID2_LIB_CHECK=0
+    fi
+
+
+    if test "$SID2_LIB_CHECK" != "0"; then
 
         if test "$PKG_CONFIG" = ""; then
 
@@ -8134,6 +8146,96 @@ Please check your installation!
 
         PKG_CONFIG_PATH=$my_save_pkg_config_path
     export PKG_CONFIG_PATH
+
+    else
+
+    echo "$as_me:$LINENO: checking for sidplay2 library and headers" >&5
+echo $ECHO_N "checking for sidplay2 library and headers... $ECHO_C" >&6
+
+    my_libdir=""
+    my_includedir=""
+    my_uname=LIB`echo sidplay2 | tr a-z A-Z`
+
+
+# Check whether --with-sidplay2-includes or --without-sidplay2-includes was given.
+if test "${with_sidplay2_includes+set}" = set; then
+  withval="$with_sidplay2_includes"
+  my_includedir="$withval"
+
+fi;
+
+
+# Check whether --with-sidplay2-library or --without-sidplay2-library was given.
+if test "${with_sidplay2_library+set}" = set; then
+  withval="$with_sidplay2_library"
+  my_libdir="$withval"
+
+fi;
+
+        if test "$my_libdir" = ""; then
+        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+        { { echo "$as_me:$LINENO: error:
+sidplay2 library path not supplied!
+        " >&5
+echo "$as_me: error:
+sidplay2 library path not supplied!
+        " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+    if test "$my_includedir" = ""; then
+        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+        { { echo "$as_me:$LINENO: error:
+sidplay2 include path not supplied!
+        " >&5
+echo "$as_me: error:
+sidplay2 include path not supplied!
+        " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+        my_dirs="$my_includedir"
+
+    my_includedir=NO
+    for i in $my_dirs; do
+        for j in sidplay/sidplay2.h; do
+            if test -r "$i/$j"; then
+                my_includedir=$i
+                if test "my_header" != ""; then
+                    my_header=$j
+                fi
+                break 2
+            fi
+        done
+    done
+
+
+    if test "$my_includedir" = NO; then
+        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+        { { echo "$as_me:$LINENO: error:
+sidplay2 headers not found!
+        " >&5
+echo "$as_me: error:
+sidplay2 headers not found!
+        " >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    eval ${my_uname}_CXXFLAGS=\"-I$my_includedir\"
+    eval ${my_uname}_LDFLAGS=\"$my_libdir/libsidplay2.la\"
+
+        if test "" != ""; then
+        =$my_header
+    fi
+
+        LIBSIDPLAY2_CXXFLAGS="$LIBSIDPLAY2_CXXFLAGS -DHAVE_UNIX"
+        LIBSIDPLAY2_PREFIX=NONE
+    fi
 
 
 
